version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - goimports # Import ordering and formatting

linters:
  default: standard
  enable:
    # Code quality
    - misspell       # Spell checking in comments and strings
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Detect unused function parameters
    - revive         # Fast, configurable, extensible linter

    # Bug detection
    - gosec          # Security-focused linting
    - bodyclose      # Check HTTP response body is closed
    - noctx          # Detect missing context.Context in HTTP requests

    # Error handling
    - errname        # Check error naming conventions
    - errorlint      # Find error wrapping issues

    # Complexity
    - gocyclo        # Cyclomatic complexity
    - nestif         # Deeply nested if statements

    # Performance
    - prealloc       # Slice preallocation suggestions

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln

    gocyclo:
      min-complexity: 30

    gosec:
      excludes:
        - G104 # Unhandled errors in deferred calls
        - G204 # Subprocess launched with variable - expected for CLI tool wrapping external tools
        - G304 # File inclusion via variable - expected for CLI tool reading user-specified files
        - G301 # Directory permissions 0750 - 0755 is standard for tool install dirs
        - G306 # WriteFile permissions 0600 - 0644 is standard for generated docs
        - G702 # Command injection via taint analysis - binary paths resolved from trusted lookups
        - G703 # Path traversal via taint - false positive on temp file reads
        - G704 # SSRF via taint - downloading from GitHub API is expected
        - G705 # XSS via taint - CLI stderr debug output, not web context

    nestif:
      min-complexity: 6

    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: increment-decrement
        - name: error-naming

  exclusions:
    rules:
      # Relax linters in test files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - gosec
          - nestif
          - revive
          - noctx

      # main.go is thin, allow unchecked errors
      - path: main\.go
        linters:
          - errcheck

      # Package name 'parser' intentionally matches its domain; renaming
      # would break all import paths for a cosmetic suggestion.
      - path: pkg/parser/
        linters:
          - revive
        text: "var-naming: avoid package names"
