name: 'Docker Documentation Generator'
description: 'Automatically generate README documentation from Dockerfiles'
author: 'northcutted'
inputs:
  config:
    description: 'Path to configuration file'
    default: 'dock-docs.yaml'
  output:
    description: 'Output file path'
    default: 'README.md'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/northcutted/dock-docs:latest'
  args:
    - "--config"
    - ${{ inputs.config }}
    - "--output"
    - ${{ inputs.output }}
