name: 'Dock-Docker: Docker Documentation Generator'
description: 'Automatically generate README documentation from Dockerfiles'
author: 'northcutted'
inputs:
  version:
    description: 'Version of dock-docs to use (e.g., v1.0.0). Defaults to latest.'
    default: 'latest'
  config:
    description: 'Path to configuration file'
    default: 'dock-docs.yaml'
  output:
    description: 'Output file path'
    default: 'README.md'

runs:
  using: "composite"
  steps:
    # 1. Setup Environment
    - name: Setup Tool Cache
      shell: bash
      run: |
        # Create a specific directory for our tools
        TOOL_DIR="$HOME/.dock-docs/bin"
        mkdir -p "$TOOL_DIR"
        
        # Add to PATH for this step and all future steps in the job
        echo "$TOOL_DIR" >> $GITHUB_PATH

    # 2. Install Dependencies (Syft, Grype, Dive)
    - name: Install Dependencies
      shell: bash
      run: |
        TOOL_DIR="$HOME/.dock-docs/bin"
        
        echo "::group::Installing Syft & Grype"
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$TOOL_DIR"
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "$TOOL_DIR"
        echo "::endgroup::"

        echo "::group::Installing Dive"
        # Dive manual install (detecting arch for runner)
        DIVE_VERSION="0.12.0"
        if [ "${{ runner.arch }}" = "ARM64" ]; then
           DIVE_ARCH="linux_arm64"
        else
           DIVE_ARCH="linux_amd64"
        fi
        
        curl -sL "https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_${DIVE_ARCH}.tar.gz" \
          | tar xz -C "$TOOL_DIR" dive
        echo "::endgroup::"

    # 3. Install Your Tool (dock-docs)
    - name: Install dock-docs
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TOOL_DIR="$HOME/.dock-docs/bin"
        echo "::group::Installing dock-docs"
        
        # 1. Map GitHub Runner OS to GoReleaser OS (title case)
        # Linux -> Linux, Darwin -> Darwin
        OS_NAME=$(uname -s)

        # 2. Map GitHub Runner Arch to GoReleaser Arch
        # X64 -> x86_64, ARM64 -> arm64
        if [ "${{ runner.arch }}" = "ARM64" ]; then
          ARCH_NAME="arm64"
        else
          ARCH_NAME="x86_64"
        fi

        # 3. Construct the asset pattern based on your goreleaser.yaml
        # Pattern: dock-docs_Linux_x86_64.tar.gz
        ASSET_PATTERN="*_${OS_NAME}_${ARCH_NAME}.tar.gz"
        
        echo "Downloading asset matching: $ASSET_PATTERN"

        # 4. Use GH CLI to download
        # If version is 'latest', we omit the tag arg to fetch latest
        if [ "${{ inputs.version }}" = "latest" ]; then
           gh release download --repo northcutted/dock-docs --pattern "$ASSET_PATTERN" --output "$TOOL_DIR/dock-docs.tar.gz" --clobber
        else
           gh release download ${{ inputs.version }} --repo northcutted/dock-docs --pattern "$ASSET_PATTERN" --output "$TOOL_DIR/dock-docs.tar.gz" --clobber
        fi

        # 5. Extract and Cleanup
        tar -xzf "$TOOL_DIR/dock-docs.tar.gz" -C "$TOOL_DIR" dock-docs
        rm "$TOOL_DIR/dock-docs.tar.gz"
        chmod +x "$TOOL_DIR/dock-docs"
        
        echo "::endgroup::"

    # 4. Run the Tool
    - name: Run dock-docs
      shell: bash
      run: |
        dock-docs --config "${{ inputs.config }}" --output "${{ inputs.output }}"