name: 'Docker Documentation Generator'
description: 'Automatically generate README documentation from Dockerfiles'
author: 'northcutted'
inputs:
  config:
    description: 'Path to configuration file'
    default: 'dock-docs.yaml'
  output:
    description: 'Output file path'
    default: 'README.md'
runs:
  using: 'composite'
  steps:
    - name: Run dock-docs
      shell: bash
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v ${{ github.workspace }}:/github/workspace \
          -w /github/workspace \
          ghcr.io/northcutted/dock-docs:latest \
          --config ${{ inputs.config }} \
          --output ${{ inputs.output }}
